apiVersion: pipeline/v1
kind: Asset
metadata:
  name: uscis-ihs-aiftdhs-report
  labels:
    domain: immigration
    frequency: yearly
    format: pdf
    fiscal_year: "2024"
spec:
  agencyRef: uscis
  description: Immigration Health Service Annual Report on Immigration Fiscal Transparency and DHS (FY2024)
  acquisition:
    type: http
    source:
      url: https://www.uscis.gov/sites/default/files/document/reports/ihsaiftdhs_fy24.pdf
    format: pdf
    schedule: "@yearly"
